public/.htaccess
The .htaccess file was missing even though the [documentation](http://lumen.laravel.com/docs/installation#pretty-urls) states that Lumen ships with one for pretty URLs with Apache.
=> Added .htaccess file (copied from laravel/laravel)

tests/ExampleTest.php
There is no "Hello World" page on the default install, just displays "Lumen." So we should just be able to assert that the response is OK to get green on a default install, similar the default test on laravel/laravel.
=> Remove check for Hello World

public/.htaccess
Add rewrite condition to the trailing slashes rewrite due to a redirect loop occurring when making a request to a public directory.
=> Trailing slashes directory condition

.gitignore
Reverts laravel/lumen#43
These storage directories already have .gitignore files and I can't see why .env.example should be ignored.
=> [5.1] Revert 3087f15

bootstrap/app.php, composer.json
I think updating the app bootstrap file like this is as a good default since we load the dependency by default, and we no longer throw the exception when the .env file doesn't exist.
=> [5.2] phpdotenv improvements

app/Providers/AuthServiceProvider.php
Since Lumen defaults to no facades.
Just little something I ran into when using lumen without facades and thought it might be beneficial to others too.
=> Changing Auth facade to app['auth']

app/Providers/AuthServiceProvider.php
The AuthServiceProvider is using `api` but this isn't a "supported" driver and is quite confusing for people upgrading as this isn't documented anywhere in the lumen docs. It makes sense to keep to the defined terminology, as shown in `lumen-framework`, if nothing is going to be documented around the feature.
This resolves https://github.com/laravel/lumen-framework/issues/319 which was closed without any consideration...
This PR ties hand-in-hand with https://github.com/laravel/lumen-framework/pull/358
=> 'API' isn't a supported driver

tests/ExampleTest.php
In assertEquals() method the parameter  `$this->app->version()` 
should be exptected and paramter `$this->response->getContent()` 
should be actual.
=> [5.2] Pass parameters to assertEquals in correct order

composer.json
I didn't see that this PR was rejected. I noticed this difference between the laravel installer and the lumen installer.
=> adding post root package install composer script

composer.json
On a fresh installation, tests that call `$this->expectsJobs([*]);` throw a `Class "Mockery\Mockery" not found` exception. Requiring Mockery fixes this!
=> Requiring Mockery

composer.json
When I try to run "composer update" for the first time, composer shows the following error:
```
Problem 1
- The requested package laravel/lumen-framework 5.3.* is satisfiable by laravel/lumen-framework[5.3.x-dev] but these conflict with your requirements or minimum-stability.
```
=> Added minimum-stability and prefer-stable

public/.htaccess
Copied from Laravel. It's necessary for token-based authentication because Apache strips the Authorization header.
See also: https://github.com/laravel/laravel/pull/3636
=> Handle authorization header

phpunit.xml
As in `laravel/laravel` - the queue driver should default to `sync` during testing?
=> Add sync queue driver to phpunit.xml

readme.md
This is the Lumen Repository, so you discover security vulnerabilities in Lumen not in Laravel.
=> This is the Lumen Repository not the Laravel Repo

.env.example
a fresh artisan call fails b/c of default memcached setting in .env file.
```
✗ php artisan 
[Symfony\Component\Debug\Exception\FatalThrowableError]  
Class 'Memcached' not found 
```
also found here: http://stackoverflow.com/questions/42024806/class-memcached-not-found-lumen-5-4
switchin this to file cache should be a better starting point
=> Fix fresh artisan error b/c of memcached default

composer.json
Updated `mockery/mockery` to `~1.0` to match Laravel [composer file](https://github.com/laravel/laravel/blob/master/composer.json#L16).
=> [5.5] Update mockery/mockery in composer.json

composer.json
Bugfix/Feature Request
I'd like to be able to use my database seeds and factories to seed my environment after doing a `composer install --no-dev` in my QA environment. 
When I run:
```sh 
composer install --no-dev --optimize-autoloader
php artisan migrate:refresh --seed
```
I get `Class DatabaseSeeder does not exist`.
I should not get this error and I should be able to seed successfully.
While this may not be a "required" change, and I can just change it in my own `composer.json` manually. I'm uncertain as to why `laravel/laravel` has a slightly different `composer.json` in this regard. If the idea was to be as a "tight" and  "performant" as possible in Lumen, I can maybe see that autoloading a few less classes may save some space, but I feel like not being able to run database seeds …
=> [5.6] Updating composer.json to allow for seeds and factories

phpunit.xml
Currently generating the following warning:
```
PHPUnit 7.2.6 by Sebastian Bergmann and contributors.
Warning - The configuration file did not pass validation!
The following problems have been detected:
Line 11:
- Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.
Test results may not be as expected.
```
=> [5.6] Remove deprecated syntaxCheck parameter.

composer.json
**This PR needs to wait until laravel/lumen-framework has PHPUnit 8 support: https://github.com/laravel/lumen-framework/pull/872**
Encourage people to use PHPUnit 8.
=> [5.8] Encourage PHPUnit 8 usage

app/Exceptions/Handler.php
When working with APIs, a JsonResponse is returned, for example, when dealing with validations.
=> [5.7] Handler::render might return a JsonResponse as well

composer.json
New Lumen apps need not require this anymore since the lumen framework will have it.
=> [5.8] No need to require phpdotenv anymore

.editorconfig
Moved changes from Laravel repository - https://github.com/laravel/laravel/pull/5090
=> [6.x] Allowing optional use of yml/yaml file extensions in .editorconfig

.gitignore
After upgrading an older lumen application, I noticed that phpunit result cache was not ignored.
I had accidentally committed this file, but I hope others didn't need to follow the same path I did ¯\_(ツ)_/¯
=> [6.x] Ignore PHPUnit result cache

bootstrap/app.php
See https://github.com/laravel/lumen-framework/pull/1014. The reason for removing the `if` that was originally in the lumen framework code is that we now match the laravel/framework behaviour, which just reads the timezone from the app config, and always sets it.
---
Related to https://github.com/laravel/lumen-framework/pull/1014.
=> [7.x] Move timezone setting to app bootstrap file

bootstrap/app.php
Changed "driectory" to "directory" within Config-Files PHPDoc block.
=> Fix spelling in PHPDoc (driectory)
