laravel/lumen

bootstrap/app.php

Fix a typo in the `app.php` file

Fix typo in app.php

---

.env.example

https://github.com/laravel/lumen-framework/pull/94

add DB_PORT option to environment variables.

---

database/seeds/DatabaseSeeder.php

Based on https://github.com/laravel/laravel/commit/03a27fa0b2e11341cc9cc61a1304f03db5b219b9

Reguard model on database seeder

---

app/Exceptions/Handler.php
app/Providers/AppServiceProvider.php
composer.json

Some small PSR-2 changes and composer.json php requirement.

Just some small PSR-2 changes

---

resources/lang/en/validation.php

Added the `string` text for validation. (Copied from laravel)

Added missing string validation text.

---

app/Exceptions/Handler.php

Removing a return that is not needed. <3

[5.1] Removing return inside ExceptionHandler

---

phpunit.xml

Same as https://github.com/laravel/laravel/commit/28ea52d10b69b5cdf6fe72fe2acb5594022e1a8e but for lumen

Update the phpunit config

---

database/seeds/DatabaseSeeder.php

Let's make it consistent with Laravel and the docs.

Update DatabaseSeeder.php example to UsersTableSeeder

---

.gitignore

Add more items to .gitignore as in Laravel.

Add more items to .gitignore as in Laravel

---

composer.json

You add mockery in lumen master, why not include in this stuff?
https://github.com/laravel/lumen/commit/93528ffef86f51008e969dcb25796669766c6c9b#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

Requiring Mockery

---

tests/ExampleTest.php

As per the Lumen docs - both `DatabaseMigrations` and `DatabaseTransactions` are listed in the `ExampleTest` - so this helps keep things aligned.

Include DatabaseMigrations in ExampleTest

---

phpunit.xml

This folder no longer exists inside `/app`

Remove old routes from phpunit.xml

---

composer.json

Fix #99, move `optimize-autoloader` option to `config` section in `composer.json` file.

Move optimize-autoloader to correct composer.json section

---

bootstrap/app.php

Needs to be 4 spaces from the start of the line above.

[5.7] Fix indentation

---

bootstrap/app.php
composer.json

Depends on https://github.com/laravel/lumen-framework/pull/877.

[5.8] Environment loading fixes

---

storage/framework/cache/data/.gitignore

Per upstream Laravel 5.8 and this Lumen update: https://github.com/laravel/lumen-framework/commit/10ab42bece74ab2e45bad7443d3fd6c1ed0bd000#diff-ef16cabd572189f548df70d3f0042c33R49

Add storage/framework/cache/data

---

bootstrap/app.php

Fixes https://github.com/laravel/lumen-framework/issues/1036.

[6.x] Added a section to bootstrap/app.php for config files

---

routes/web.php

I added the type for $router similar to `database/factories/ModelFactory.php` so IDEs can help with autocomplete

[7.x] Add type hint for $router for autocomplete

---

phpunit.xml

See: https://github.com/laravel/framework/blob/7.x/phpunit.xml.dist#L14

[7.x] Normalize Style

---

composer.json

In addition to the changes made on the main lumen-framework repo.

[9.x] Bump to PHP 7.4
